# Build settings
title: Travel Log
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
search_enabled: true
search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
color_scheme: colors
logo: "./images/logo3.png"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: red
